// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetmonWhitelistKey struct {
	_         structs.HostLayout
	PrefixLen uint32
	Ip        uint32
}

type NetmonWhitelistValue struct {
	_         structs.HostLayout
	Ports     [16]uint16
	PortCount uint8
	_         [1]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	NetmonMapActiveMap      = "active_map"
	NetmonMapBlockEvents    = "block_events"
	NetmonMapDropCounter    = "drop_counter"
	NetmonMapPolicyVersion  = "policy_version"
	NetmonMapWhitelistA     = "whitelist_a"
	NetmonMapWhitelistB     = "whitelist_b"
	NetmonProgGozcuConnect4 = "gozcu_connect4"
	NetmonProgGozcuConnect6 = "gozcu_connect6"
)

// LoadNetmon returns the embedded CollectionSpec for Netmon.
func LoadNetmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Netmon: %w", err)
	}

	return spec, err
}

// LoadNetmonObjects loads Netmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetmonObjects
//	*NetmonPrograms
//	*NetmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetmonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetmonSpecs struct {
	NetmonProgramSpecs
	NetmonMapSpecs
	NetmonVariableSpecs
}

// NetmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetmonProgramSpecs struct {
	GozcuConnect4 *ebpf.ProgramSpec `ebpf:"gozcu_connect4"`
	GozcuConnect6 *ebpf.ProgramSpec `ebpf:"gozcu_connect6"`
}

// NetmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetmonMapSpecs struct {
	ActiveMap     *ebpf.MapSpec `ebpf:"active_map"`
	BlockEvents   *ebpf.MapSpec `ebpf:"block_events"`
	DropCounter   *ebpf.MapSpec `ebpf:"drop_counter"`
	PolicyVersion *ebpf.MapSpec `ebpf:"policy_version"`
	WhitelistA    *ebpf.MapSpec `ebpf:"whitelist_a"`
	WhitelistB    *ebpf.MapSpec `ebpf:"whitelist_b"`
}

// NetmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetmonVariableSpecs struct {
}

// NetmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetmonObjects struct {
	NetmonPrograms
	NetmonMaps
	NetmonVariables
}

func (o *NetmonObjects) Close() error {
	return _NetmonClose(
		&o.NetmonPrograms,
		&o.NetmonMaps,
	)
}

// NetmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetmonMaps struct {
	ActiveMap     *ebpf.Map `ebpf:"active_map"`
	BlockEvents   *ebpf.Map `ebpf:"block_events"`
	DropCounter   *ebpf.Map `ebpf:"drop_counter"`
	PolicyVersion *ebpf.Map `ebpf:"policy_version"`
	WhitelistA    *ebpf.Map `ebpf:"whitelist_a"`
	WhitelistB    *ebpf.Map `ebpf:"whitelist_b"`
}

func (m *NetmonMaps) Close() error {
	return _NetmonClose(
		m.ActiveMap,
		m.BlockEvents,
		m.DropCounter,
		m.PolicyVersion,
		m.WhitelistA,
		m.WhitelistB,
	)
}

// NetmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetmonVariables struct {
}

// NetmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetmonPrograms struct {
	GozcuConnect4 *ebpf.Program `ebpf:"gozcu_connect4"`
	GozcuConnect6 *ebpf.Program `ebpf:"gozcu_connect6"`
}

func (p *NetmonPrograms) Close() error {
	return _NetmonClose(
		p.GozcuConnect4,
		p.GozcuConnect6,
	)
}

func _NetmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netmon_bpfeb.o
var _NetmonBytes []byte
